artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://github.com/Adi-04/Nidarshan/raw/main/Data/full_data.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion